# Generated by Django 4.1.1 on 2022-09-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoFacility',
            fields=[
                ('cf_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=30)),
                ('fac_popu', models.BigIntegerField(blank=True, null=True)),
                ('qur_rate', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoPopuDensity',
            fields=[
                ('cp_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=30)),
                ('popu_density', models.BigIntegerField(blank=True, null=True)),
                ('qur_rate', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_popu_density',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoVaccine',
            fields=[
                ('cv_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=30)),
                ('v1th_rate', models.BigIntegerField(blank=True, null=True)),
                ('v2th_rate', models.BigIntegerField(blank=True, null=True)),
                ('v3th_rate', models.BigIntegerField(blank=True, null=True)),
                ('v4th_rate', models.BigIntegerField(blank=True, null=True)),
                ('qur_rate', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_vaccine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoWeekday',
            fields=[
                ('cw_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('sun', models.BigIntegerField(blank=True, null=True)),
                ('mon', models.BigIntegerField(blank=True, null=True)),
                ('tue', models.BigIntegerField(blank=True, null=True)),
                ('wed', models.BigIntegerField(blank=True, null=True)),
                ('thu', models.BigIntegerField(blank=True, null=True)),
                ('fri', models.BigIntegerField(blank=True, null=True)),
                ('sat', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_weekday',
                'managed': False,
            },
        ),
    ]
